FROM python:3.10-slim

RUN apt-get update && apt-get install -y --no-install-recommends curl libgomp1 && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir pymupdf sentence-transformers qdrant-client

WORKDIR /app

COPY models/all-MiniLM-L6-v2 /app/models/all-MiniLM-L6-v2
COPY metadata_master.json /app/metadata_master.json
COPY src/etl/text_extractor.py /app/text_extractor.py
COPY src/etl/wait-and-indexer.sh /app/wait-and-indexer.sh

RUN chmod +x /app/wait-and-indexer.sh

CMD ["/app/wait-and-indexer.sh"]